[package]
name = "option_struct_modules"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ulid = "1.0.0"
bigdecimal = "0.3.1"
